### ISSUE TITLE
User Story: Home Page

### ISSUE THREAD

**Issue by BilalEssafi1** [BilalEssafi1/dar-tangier-project#15]
As a visitor, I can view the home page, so I can learn more about Dar Tangier and see the restaurant menu and find the location.

Acceptance Criteria:

- The home page displays a hero image, restaurant name, description, about section, menu section and call-to-action buttons (View Menu, Sign Up/Log In).
- Footer includes contact details and social media links.
- Menu items are displayed with images, descriptions, and prices.
- The menu is organized into categories (e.g., Starters, Main Courses, Desserts).
- Accessible to all users, logged in or not.
- The location is displayed on Google maps on the website. 
- I can contact the restaurant via email.
Tasks:

- [x] Design and implement the home page structure.
- [x] Develop a "Menu" page with organized dishes.
- [x] Implement Google Maps API to showcase restaurant location
- [x] Add contact form that roots message to restaurant email
- [x] Ensure mobile responsiveness and styling using Bootstrap and CSS.

**Comment by BilalEssafi1** [comment]
Include about section intro section of main page

**Comment by BilalEssafi1** [comment]
Ensure contact form doesn't allow empty submissions
